-- =============================================================================
-- DVB-T2 MI BBFRAME Extractor and TS Rebuilder (TS Parser)
--
-- Author : Xabier Legaspi Juanatey
-- Date   : 2026-06-04
--
-- This module parses MPEG-2 Transport Stream (TS) packets carrying DVB-T2
-- Modulator Interface (T2-MI) data on a selected PID. It identifies and
-- extracts the T2-MI payload section from the transport stream and forwards
-- valid payload bytes to the T2-MI parser for BBFRAME processing.
--
-- It performs:
--   - Transport stream synchronization using sync byte detection (0x47)
--   - PID extraction and filtering against the configured target PID
--   - Payload Unit Start Indicator (PUSI) processing
--   - Continuity counter validation
--   - Adaptation field parsing and skipping
--   - Pointer field processing and section alignment
--   - Forwarding of valid T2-MI payload bytes
--   - Detection of malformed TS packets and protocol violations
--
-- The parser coordinates packet processing with the T2-MI parser through a
-- control/status interface. It enables payload forwarding when a valid T2-MI
-- packet is detected and responds to skip or error requests generated by the
-- downstream T2-MI decoder.
--
-- Interfaces:
--   - Input MPEG-TS stream (clock, sync, valid, data)
--   - Target PID selection interface
--   - Status inputs from the T2-MI parser (skip/error)
--   - Control outputs toward the T2-MI parser (run/error)
--
-- State Machine:
--   SYNC               : Verify TS sync byte
--   PID_H / PID_L      : Extract and validate PID
--   CC_AFC             : Validate continuity counter and AFC
--   ADAPTATION_LENGTH  : Read adaptation field length
--   ADAPTATION_FIELD   : Skip adaptation field bytes
--   POINTER_FIELD      : Read pointer field value
--   POINTER_SECTION    : Skip bytes before T2-MI section start
--   PAYLOAD            : Forward T2-MI payload bytes
--   T2MI_*             : Error and recovery handling
--
-- Notes:
--   - Designed for DVB-T2 T2-MI streams encapsulated in MPEG-TS packets.
--   - Supports adaptation field and payload-only packet formats.
--   - Maintains continuity counter tracking across packets.
--   - Ensures section alignment using PUSI and pointer field processing.
-- =============================================================================

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity ts_parser is
    port (
        clk_i                       : in std_logic;
        rst_i                       : in std_logic;

        -- Input transport stream interface
        ts_clk_i                    : in std_logic;
        ts_sync_i                   : in std_logic;
        ts_valid_i                  : in std_logic;
        ts_data_i                   : in std_logic_vector(7 downto 0);
        ts_target_pid_i             : in std_logic_vector(12 downto 0);
        ts_target_pid_received_i    : in std_logic;

        -- Status from T2-MI parser
        t2mi_receive_skip_i         : in std_logic;
        t2mi_receive_error_i        : in std_logic;

        -- Control toward T2-MI parser
        t2mi_run_o                  : out std_logic := '0';
        t2mi_send_error_o           : out std_logic := '0'
    );
end entity;

architecture rtl of ts_parser is

    -----------------------------------------------------------------------------
    -- Constants
    -----------------------------------------------------------------------------
    constant C_SYNC_BYTE                    : std_logic_vector(7 downto 0) := x"47";
    constant C_PUSI_INDEX                   : integer                      := 6; -- Bit index of PUSI in the second TS packet byte.
    constant C_POINTER_FIELD_H              : unsigned(7 downto 0)         := to_unsigned(184, 8);
    constant C_187                          : integer                      := 187;

    -----------------------------------------------------------------------------
    -- State Machine
    -----------------------------------------------------------------------------
    type t_state is (
            SYNC,
            PID_H,
            PID_L,
            CC_AFC,
            ADAPTATION_LENGTH,
            ADAPTATION_FIELD,
            POINTER_FIELD,
            POINTER_SECTION,
            PAYLOAD,
            T2MI_RECEIVE_SKIP,
            T2MI_RECEIVE_ERROR,
            T2MI_SEND_ERROR
        );

    -----------------------------------------------------------------------------
    -- Parser State and Counters
    -----------------------------------------------------------------------------
    signal s_state                          : t_state                       := SYNC;
    signal s_init                           : std_logic                     := '1';
    signal s_cnt_tsp_byte                   : integer range 0 to 187        := C_187;
    signal s_pusi                           : std_logic                     := '0';
    signal s_pid                            : std_logic_vector(12 downto 0) := (others => '0');
    signal s_cc_next                        : std_logic_vector(3 downto 0)  := (others => '0');
    signal s_cnt_adaptation_length          : unsigned(7 downto 0)          := (others => '0');
    signal s_cnt_pointer_field              : unsigned(7 downto 0)          := (others => '0');

    -----------------------------------------------------------------------------
    -- Transport Stream Input Pipeline
    -----------------------------------------------------------------------------
    -- Register transport stream inputs into the local clock domain.
    signal s_ts_clk_reg1                    : std_logic                     := '0';
    signal s_ts_clk_reg2                    : std_logic                     := '0';
    signal s_ts_sync_reg1                   : std_logic                     := '0';
    signal s_ts_valid_reg1                  : std_logic                     := '0';
    signal s_ts_data_reg1                   : std_logic_vector(7 downto 0)  := (others => '0');
    signal s_ts_target_pid_reg1             : std_logic_vector(12 downto 0) := (others => '0');
    signal s_ts_target_pid_received_reg1    : std_logic                     := '0';

begin

    process (clk_i, rst_i)
    begin
        if rst_i = '1' then
            -- Reset parser state.
            s_state                 <= SYNC;
            s_init                  <= '1';
            s_cnt_tsp_byte          <= C_187;
            s_pusi                  <= '0';
            s_pid                   <= (others => '0');
            s_cc_next               <= (others => '0');
            s_cnt_adaptation_length <= (others => '0');
            s_cnt_pointer_field     <= (others => '0');

            -- Reset outputs.
            t2mi_run_o          <= '0';
            t2mi_send_error_o   <= '0';

        elsif rising_edge(clk_i) then

            -----------------------------------------------------------------------------
            -- Transport Stream Input Registration
            -----------------------------------------------------------------------------
            -- Register input transport stream signals.
            s_ts_clk_reg1                   <= ts_clk_i;
            s_ts_clk_reg2                   <= s_ts_clk_reg1;
            s_ts_sync_reg1                  <= ts_sync_i;
            s_ts_valid_reg1                 <= ts_valid_i;
            s_ts_data_reg1                  <= ts_data_i;
            s_ts_target_pid_reg1            <= ts_target_pid_i;
            s_ts_target_pid_received_reg1   <= ts_target_pid_received_i;

            -- Handle skip requests from the T2-MI parser.
            if t2mi_receive_skip_i = '1' then
                s_state     <= T2MI_RECEIVE_SKIP;
                t2mi_run_o  <= '0';

            -- Handle error indications from the T2-MI parser.
            elsif t2mi_receive_error_i = '1' then
                s_state     <= T2MI_RECEIVE_ERROR;
                t2mi_run_o  <= '0';

            else

                case s_state is
                    -- -------------------------------------------------------
                    -- SYNC: wait for 0x47 sync byte on the selected PID stream
                    -- -------------------------------------------------------
                    when SYNC =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_sync_reg1  = '1'   and
                            s_ts_valid_reg1 = '1')  then

                            -- Verify transport stream sync byte.
                            if s_ts_data_reg1 = C_SYNC_BYTE then
                                s_state           <= PID_H;
                                s_cnt_tsp_byte    <= s_cnt_tsp_byte - 1;
                                t2mi_send_error_o <= '0';
                            else
                                s_state           <= T2MI_SEND_ERROR;
                                s_cnt_tsp_byte    <= C_187;
                                t2mi_send_error_o <= '1';
                            end if;
                        end if;

                    -- -------------------------------------------------------
                    -- PID_H: capture PUSI flag and high PID bits
                    -- -------------------------------------------------------
                    when PID_H =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if s_init = '0' or s_ts_data_reg1(C_PUSI_INDEX) = '1' then
                                s_state             <= PID_L;
                                s_cnt_tsp_byte      <= s_cnt_tsp_byte - 1;
                                s_pusi              <= s_ts_data_reg1(C_PUSI_INDEX);
                                s_pid(12 downto 8)  <= s_ts_data_reg1(4 downto 0);
                            else
                                s_state             <= SYNC;
                                s_cnt_tsp_byte      <= C_187;
                                s_pusi              <= '0';
                                s_pid               <= (others => '0');
                            end if;
                        end if;

                    -- -------------------------------------------------------
                    -- PID_L: complete PID and verify against the target PID
                    -- -------------------------------------------------------
                    when PID_L =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if (s_pid(12 downto 8) & s_ts_data_reg1) = s_ts_target_pid_reg1 then
                                s_state             <= CC_AFC;
                                s_cnt_tsp_byte      <= s_cnt_tsp_byte - 1;
                                s_pid(7 downto 0)   <= s_ts_data_reg1;
                            else
                                s_state             <= SYNC;
                                s_cnt_tsp_byte      <= C_187;
                                s_pid               <= (others => '0');
                            end if;
                        end if;

                    -- -------------------------------------------------------
                    -- CC_AFC: validate continuity counter and AFC field
                    -- -------------------------------------------------------
                    when CC_AFC =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            -- Check continuity counter sequence.
                            if s_init = '0' and (s_ts_data_reg1(3 downto 0) /= s_cc_next) then
                                s_state                     <= T2MI_SEND_ERROR;
                                s_cnt_tsp_byte              <= C_187;
                                s_cc_next                   <= (others => '0');
                                t2mi_run_o                  <= '0';
                                t2mi_send_error_o           <= '1';
                            else
                                -- Decode adaptation field control.
                                case s_ts_data_reg1(5 downto 4) is
                                    when "01" =>
                                        -- Payload only.
                                        if s_pusi = '1' then
                                            s_state         <= POINTER_FIELD;
                                            t2mi_run_o      <= '0';
                                        else
                                            s_state         <= PAYLOAD;
                                            t2mi_run_o      <= '1';
                                        end if;
                                        s_cnt_tsp_byte      <= s_cnt_tsp_byte - 1;
                                        s_cc_next           <= std_logic_vector((unsigned(s_ts_data_reg1(3 downto 0)) + 1) mod 16);
                                        t2mi_send_error_o   <= '0';

                                    when "10" =>
                                        -- Adaptation field only.
                                        s_state             <= SYNC;
                                        s_cnt_tsp_byte      <= C_187;
                                        s_cc_next           <= std_logic_vector((unsigned(s_ts_data_reg1(3 downto 0)) + 1) mod 16);
                                        t2mi_run_o          <= '0';
                                        t2mi_send_error_o   <= '0';

                                    when "11" =>
                                        -- Adaptation field followed by payload.
                                        s_state             <= ADAPTATION_LENGTH;
                                        s_cnt_tsp_byte      <= s_cnt_tsp_byte - 1;
                                        s_cc_next           <= std_logic_vector((unsigned(s_ts_data_reg1(3 downto 0)) + 1) mod 16);
                                        t2mi_run_o          <= '0';
                                        t2mi_send_error_o   <= '0';

                                    when others =>
                                        -- Reserved AFC value.
                                        s_state             <= T2MI_SEND_ERROR;
                                        s_cnt_tsp_byte      <= C_187;
                                        s_cc_next           <= (others => '0');
                                        t2mi_run_o          <= '0';
                                        t2mi_send_error_o   <= '1';
                                end case;
                            end if;
                        end if;

                    -- -------------------------------------------------------
                    -- ADAPTATION_LENGTH: read adaptation field length
                    -- -------------------------------------------------------
                    when ADAPTATION_LENGTH =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if unsigned(s_ts_data_reg1) = 0 and s_pusi = '1' then
                                s_state <= POINTER_FIELD;
                            elsif unsigned(s_ts_data_reg1) = 0 and s_pusi = '0' then
                                s_state <= PAYLOAD;
                            else
                                s_state <= ADAPTATION_FIELD;
                            end if;
                            s_cnt_tsp_byte          <= s_cnt_tsp_byte - 1;
                            s_cnt_adaptation_length <= unsigned(s_ts_data_reg1);
                        end if;

                    -- -------------------------------------------------------
                    -- ADAPTATION_FIELD: skip adaptation field bytes
                    -- -------------------------------------------------------
                    when ADAPTATION_FIELD =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if s_pusi = '1' and s_cnt_adaptation_length = 1 then
                                s_state <= POINTER_FIELD;
                                s_init  <= s_init;
                            elsif s_pusi = '0' and s_cnt_adaptation_length = 1 then
                                s_state <= PAYLOAD;
                                s_init  <= '0';
                            else
                                s_state <= ADAPTATION_FIELD;
                                s_init  <= s_init;
                            end if;
                            s_cnt_tsp_byte          <= s_cnt_tsp_byte - 1;
                            s_cnt_adaptation_length <= s_cnt_adaptation_length - 1;
                        end if;

                    -- -------------------------------------------------------
                    -- POINTER_FIELD: read pointer_field value
                    -- -------------------------------------------------------
                    when POINTER_FIELD =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if unsigned(s_ts_data_reg1) = 0 then
                                s_state             <= PAYLOAD;
                                s_init              <= '0';
                                t2mi_run_o          <= '1';
                                t2mi_send_error_o   <= '0';
                            elsif unsigned(s_ts_data_reg1) > C_POINTER_FIELD_H then
                                s_state             <= T2MI_SEND_ERROR;
                                s_init              <= '1';
                                t2mi_run_o          <= '0';
                                t2mi_send_error_o   <= '1';
                            else
                                s_state             <= POINTER_SECTION;
                                if s_init = '1' then
                                    -- Wait for the first T2-MI packet start.
                                    t2mi_run_o <= '0';
                                else
                                    t2mi_run_o <= '1';
                                end if;
                                t2mi_send_error_o   <= '0';
                            end if;
                            s_cnt_tsp_byte      <= s_cnt_tsp_byte - 1;
                            s_cnt_pointer_field <= unsigned(s_ts_data_reg1);
                        end if;

                    -- -------------------------------------------------------
                    -- POINTER_SECTION: skip bytes before section start
                    -- -------------------------------------------------------
                    when POINTER_SECTION =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if s_init = '0' and s_cnt_pointer_field = 1 then
                                s_state    <= PAYLOAD;
                                t2mi_run_o <= '1';
                            elsif s_init = '0' and s_cnt_pointer_field > 1 then
                                s_state    <= POINTER_SECTION;
                                t2mi_run_o <= '1';
                            elsif s_init = '1' and s_cnt_pointer_field = 1 then
                                s_state    <= PAYLOAD;
                                s_init     <= '0';
                                t2mi_run_o <= '1';
                            else
                                s_state    <= POINTER_SECTION;
                                t2mi_run_o <= '0';
                            end if;
                            s_cnt_tsp_byte      <= s_cnt_tsp_byte - 1;
                            s_cnt_pointer_field <= s_cnt_pointer_field - 1;
                        end if;

                    -- -------------------------------------------------------
                    -- PAYLOAD: forward payload bytes to the T2-MI parser
                    -- -------------------------------------------------------
                    when PAYLOAD =>
                        if (s_ts_clk_reg1   = '1'   and
                            s_ts_clk_reg2   = '0'   and
                            s_ts_valid_reg1 = '1')  then

                            if s_cnt_tsp_byte = 0 then
                                s_state         <= SYNC;
                                s_cnt_tsp_byte  <= C_187;
                                s_init          <= '0';
                                t2mi_run_o      <= '0';
                            else
                                s_state         <= PAYLOAD;
                                s_cnt_tsp_byte  <= s_cnt_tsp_byte - 1;
                                t2mi_run_o      <= '1';
                            end if;
                        end if;

                    -- -------------------------------------------------------
                    -- Error and recovery states
                    -- -------------------------------------------------------
                    when T2MI_RECEIVE_SKIP | T2MI_RECEIVE_ERROR | T2MI_SEND_ERROR =>
                        -- Reinitialize parser state.
                        s_state                         <= SYNC;
                        s_init                          <= '1';
                        s_cnt_tsp_byte                  <= C_187;
                        s_pusi                          <= '0';
                        s_pid                           <= (others => '0');
                        s_cc_next                       <= (others => '0');
                        s_cnt_adaptation_length         <= (others => '0');
                        s_cnt_pointer_field             <= (others => '0');

                        -- Clear outputs.
                        t2mi_run_o                  <= '0';
                        t2mi_send_error_o           <= '0';

                end case;
            end if;
        end if;
    end process;

end architecture;