-- ram_up.vhd

-- Generated using ACDS version 19.4 64

library IEEE;
library ram_2port_2000;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ram_up is
	port (
		data      : in  std_logic_vector(7 downto 0) := (others => '0'); --      data.datain
		q         : out std_logic_vector(7 downto 0);                    --         q.dataout
		wraddress : in  std_logic_vector(9 downto 0) := (others => '0'); -- wraddress.wraddress
		rdaddress : in  std_logic_vector(9 downto 0) := (others => '0'); -- rdaddress.rdaddress
		wren      : in  std_logic                    := '0';             --      wren.wren
		wrclock   : in  std_logic                    := '0';             --   wrclock.clk
		rdclock   : in  std_logic                    := '0';             --   rdclock.clk
		rden      : in  std_logic                    := '0'              --      rden.rden
	);
end entity ram_up;

architecture rtl of ram_up is
	component ram_up_ram_2port_2000_u6dyzda_cmp is
		port (
			data      : in  std_logic_vector(7 downto 0) := (others => 'X'); -- datain
			q         : out std_logic_vector(7 downto 0);                    -- dataout
			wraddress : in  std_logic_vector(9 downto 0) := (others => 'X'); -- wraddress
			rdaddress : in  std_logic_vector(9 downto 0) := (others => 'X'); -- rdaddress
			wren      : in  std_logic                    := 'X';             -- wren
			wrclock   : in  std_logic                    := 'X';             -- clk
			rdclock   : in  std_logic                    := 'X';             -- clk
			rden      : in  std_logic                    := 'X'              -- rden
		);
	end component ram_up_ram_2port_2000_u6dyzda_cmp;

	for ram_2port_0 : ram_up_ram_2port_2000_u6dyzda_cmp
		use entity ram_2port_2000.ram_up_ram_2port_2000_u6dyzda;
begin

	ram_2port_0 : component ram_up_ram_2port_2000_u6dyzda_cmp
		port map (
			data      => data,      --      data.datain
			q         => q,         --         q.dataout
			wraddress => wraddress, -- wraddress.wraddress
			rdaddress => rdaddress, -- rdaddress.rdaddress
			wren      => wren,      --      wren.wren
			wrclock   => wrclock,   --   wrclock.clk
			rdclock   => rdclock,   --   rdclock.clk
			rden      => rden       --      rden.rden
		);

end architecture rtl; -- of ram_up
